import { BaseCURD, SearchWhere } from ".";
import { Dics } from "./Dics";


// Generated by https://quicktype.io

export class DicsType {
    TID = 0
    Name = ""
    Code = ""
    AID = 0
    GID = 0
    Key = ""
    CUID = 0
    CTime = ""
    UTime = ""
}


class DicType extends BaseCURD<DicsType> {
    Name: string = "Dics/Type"
}
const DicTypeApi = new DicType
export default DicTypeApi